name: SpoCo North West Time Trial Series
markdown: redcarpet
highlighter: pygments # pygments or rouge or null
exclude: ["node_modules", "gruntfile.js", "gulpfile.js", "package.json", ".git"]
baseurl: /spoco-nw
url: http://spoco-nw.dev
sass:
    sass_dir: css
