name: SpoCo North West Time Trial Series
markdown: redcarpet
highlighter: null # pygments or rouge or null
exclude: ["node_modules", "gruntfile.js", "gulpfile.js", "package.json", ".git"]
sass:
    sass_dir: css
